# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2025-05-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20250503_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Editor'),
        ),
    ]
